spring:
  application:
    name: group-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lms_db}
    username: ${DB_USER:lms_user}
    password: ${DB_PASSWORD:lms_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8083}

# Настройки других сервисов
services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8082}
  course:
    url: ${COURSE_SERVICE_URL:http://localhost:8080}

# Настройки логирования
logging:
  level:
    com.example.lms.groups: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"